version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
      args:
        # Use backend port exposed by compose for the browser. Adjust for remote deployments.
        VITE_API_BASE_URL: http://localhost:3001/api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/database/hyper-context.db
      - SEED=true
    volumes:
      - ./database:/app/database
      - ./logs:/app/logs
    restart: unless-stopped

volumes: {}
